name: Format code

on:
  push:
    branches: [ master ]
    
jobs:
  black-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Format code with black
        run: |
          pip install black
          black .
      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          author_name: ${{ github.actor }}
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: "[chore] Formatting code by Black standards"
          add: "."
          branch: ${{ github.ref }}
  pylint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - run: pip install --upgrade pip
    - run: pip install -r requirements.txt
    - run: pylint --disable=all --enable=unused-import $(git ls-files '*.py')